# Generated by Django 3.2.8 on 2021-10-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticker_symbol', models.CharField(max_length=10)),
                ('animal_testing', models.BooleanField()),
                ('nuclear_weapons', models.BooleanField()),
                ('coal_power', models.BooleanField()),
                ('rainforest_destruction', models.BooleanField()),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['name'], name='companies_name_c7a1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['ticker_symbol'], name='companies_ticker__2a5ea3_idx'),
        ),
    ]
